### ISSUE TITLE
# 一个疑问

### ISSUE THREAD

**Issue by OvOYu** [DrownFish19/CorrSTN#1]
https://github.com/DrownFish19/CorrSTN/blob/master/train_CorrSTN.py#L157 你好 为什么先计算验证集的误差呢 没搞懂 谢谢

**Comment by DrownFish19** [comment]
> https://github.com/DrownFish19/CorrSTN/blob/master/train_CorrSTN.py#L157 你好 为什么先计算验证集的误差呢 没搞懂 谢谢

当start_epoch不是0的时候，会从上次停止或者中间某个已保存的模型开始训练。在train之前算一次eval，会设置当前模型为最佳，否则一个epoch之后，不论精度是否上升，都会设置训练后模型为最佳。

**Comment by OvOYu** [comment]
谢谢您的回复！

**Comment by OvOYu** [comment]
谢谢您的代码，对我的帮助很大。不知道您是否还从事交通预测方便的要求，最近我正从事这方面的研究，能否加个联系，绝对不会打扰您，感谢！

**Comment by OvOYu** [comment]
在训练时您是否有设置随机种子呢

**Comment by OvOYu** [comment]
设置种子的话，是不是应该单独把种子设置在train_main里，谢谢！

**Comment by DrownFish19** [comment]
> 在训练时您是否有设置随机种子呢

我在代码里没有设置seed，每次都是随机的。如果需要设置，可以全局设置，添加在此处即可https://github.com/DrownFish19/CorrSTN/blob/de9e613836b53171487fae68450d3caab4521d48/train_CorrSTN.py#L15

**Comment by OvOYu** [comment]
谢谢！我在训练时发现并没有生成像您一样的文件夹以及log文件，请问下您如何生成log的呢

**Comment by DrownFish19** [comment]
> 谢谢！我在训练时发现并没有生成像您一样的文件夹以及log文件，请问下您如何生成log的呢

1. 运行`train_CorrSTN.py`文件之后，应该会在`experiment`文件夹下生成对应的文件夹用于保存模型。
2. 文件夹：程序运行结束之后，我会将运行结果（MAE，RMSE和MAPE）添加到文件夹名称最后，方便查询。
3. log文件：一部分程序通过学校高性能计算平台运行，会自动生成log文件，例如`slurm-xxxx.out`；一部分程序使用`nohup python train_CorrSTN.py --config xxxx > log.txt &`生成保存, log会保存在`log.txt`中。

**Comment by OvOYu** [comment]
谢谢您详细的回复 我明白了！祝您一切顺利！
