### ISSUE TITLE
关于HZMetro数据集的一些疑问

### ISSUE THREAD

**Issue by ZhangYuan1998** [DrownFish19/CorrSTN#2]
您好！非常感谢您的开源！
关于工作中使用HZMetro数据集有一些疑问。
想咨询您一下，HZMetro数据集和https://arxiv.org/pdf/2001.04889.pdf这篇文章中用的数据集是一个吗？时间范围和节点数量都能对上。但是2001.04889这个文章是15分钟作为采样频率，而且每天的采样范围是5:15 - 23:30。
想问下您在处理数据集时用的采样频率和范围是多少？
期待您的回复，祝您一切顺利！

**Comment by DrownFish19** [comment]
您好，针对数据问题有以下几点说明：
1. HZMetro数据集最原始数据来自 [全球城市计算AI挑战赛-地铁乘客流量预测](https://tianchi.aliyun.com/competition/entrance/231708/information)。因为本人没有参赛，所以现在数据已经无法再下载。
2. 本文使用的数据集由ASTGNN作者提供，经过和原始数据集比较，ASTGNN作者已经将数据转换为5分钟的采样频率。
3. 问题中提到的[文章](https://arxiv.org/pdf/2001.04889.pdf)可能使用了相同的原始数据集，但是处理方式不同。并且，在实际中，凌晨地铁无人进出，预测没有实际意义，所以作者删除了这段数据，因此仅保留5:15至23:30数据的处理方式是正确的。同理，本文在计算过程中也是仅计算6:00-24:00的数据。
